### ISSUE TITLE
[BUG] Input numbers shouldn't have type number

### ISSUE THREAD

**Issue by rfoel** [Gympass/yoga#118]
**Describe the bug**
There's a lot against using `type="number"`. Please read the following article:

https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

For instance, I am able to type the letter `e` within the input. That can break things. Also, the user can accidentally hit arrow up or arrow down (or even scroll) and increase/decrease the number. This also breaks a credit card input for example.

**Expected behavior**
The user should only be able to input numbers.

**Screenshots**

![image](https://user-images.githubusercontent.com/19496473/75985847-cb46ac80-5ecb-11ea-9ed3-f8d74f3cdacd.png)

**Comment by ggdaltoso** [comment]
Hi, @rfoel ! Thanks for bringing us this subject. 

In my honest opinion, there is nothing wrong with the `Input.Number` when you talk about the "e" character, specifically.

This behavior is intentional and common in any browser since this special character "e" or "E" is used to do a [scientific notation](https://en.wikipedia.org/wiki/Scientific_notation) of a number, instead of writing all zeros:

```
// Avogadro constant
6.022E23 == 6.022e23 == 6022000000000000000000000
```

Also, when you press the arrow up or arrow down, you will change the input value, following the step attribute, if it exists, or increasing/decreasing by 1 (default). From the [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) documentation, we can see this is the default behavior and, as you said, could be changed by the mouse scroll as well.

If you wanna need to change this behavior, you can simply handle the _keydown_ event ([codesandbox](https://codesandbox.io/s/dreamy-germain-nvlpv)):

```JSX
<Input.Number label="Number"
  onKeyDown={e => {
    const arrows = { up: 38, down: 40 };
    if (e.which === arrows.up || e.which === arrows.down) {
      e.preventDefault();
    }
  }}
/>
```

Talking about the credit card input, we are currently studying the best approach to add masks to our inputs. Stay tuned as it could help with your needs.
