### ISSUE TITLE
[FEAT] Typescript definitions file

### ISSUE THREAD

**Issue by scrous** [gympass/yoga#203]
**Is your feature request related to a problem? Please describe.**
Installing @gympass/yoga on a cra react ts project gives the following message: 
```
Could not find a declaration file for module '@gympass/yoga'. '/node_modules/@gympass/yoga/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/gympass__yoga` if it exists or add a new declaration (.d.ts) file containing `declare module '@gympass/yoga';`ts(7016)`
```

**Describe the solution you'd like**
Create a typescript definition file and push it to @types/gympass__yoga, this will assist with development on react js projects as well.

**Describe alternatives you've considered**
For now the alternative solution can be used to remove the warning, create a d.ts file and add `declare module '@gympass/yoga';` to it. But autoimport suggestions on components are not available.

**Comment by caiotracera** [comment]
Hey @scrous,

Hope you're doing well! 🌟
Just wanted to give you a heads-up that it seems like this issue has taken a bit of a nap and gone MIA. 😴 Since we're doing some cleanup, we're going to close it for now.

No worries though! If you think there's still life in it or if you've got more info to share, feel free to wake it up by reopening. Your input is always appreciated!
