### ISSUE TITLE
[BUG] Dropdown options are not selectable through keyboard

### ISSUE THREAD

**Issue by heyvito** [gympass/yoga#247]
**Describe the bug**
When opening a native dropdown, one can always begin typing to find an option:

https://user-images.githubusercontent.com/77198/116408798-9a30e600-a809-11eb-8988-cdea5ee4af3c.mp4

(Example available at [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select))

On the capture, I clicked the select, and began typing `Par`. Other interactions were made pressing spacebar to open the select, and again typing the desired option.

**To Reproduce**
1. Go to 'https://gympass.github.io/yoga/components/dropdown'
2. Open the dropdown by clicking it.
3. Try to select `Run`, for instance, by typining <kbd>R</kbd>
4. Notice no option is selected.

**Expected behavior**

**Screenshots**

**Desktop**
 - OS: macOS 11.2.3 (20D91)
 - Browser: Firefox Nightly
 - Version 90.0a1 (2021-04-28) (64-bit)
<sub>...But this will happen on any browser, in any environment</sub>

**Comment by caiotracera** [comment]
Hey @heyvito,

Hope you're doing well! 🌟
Just wanted to give you a heads-up that it seems like this issue has taken a bit of a nap and gone MIA. 😴 Since we're doing some cleanup, we're going to close it for now.

No worries though! If you think there's still life in it or if you've got more info to share, feel free to wake it up by reopening. Your input is always appreciated!
