### ISSUE TITLE
[BUG] `textAlign` system property not working correctly on Native for the `<Text />` (and variations) components.

### ISSUE THREAD

**Issue by tcK1** [gympass/yoga#368]
**Describe the bug**
Adding the prop `ta` or `textAlign` does nothing.

**To Reproduce**
1. Add the prop `ta` or `textAlign` to a `<Text />` component.

**Expected behavior**
The property should be applied.

**Screenshots**

<table>
<tr>
	<td>

```jsx
<Text
  mt="small"
  mb="xlarge"
  ta="center"
>
  My text
</Text>
```

   </td>
	<td>

![image](https://user-images.githubusercontent.com/9873486/136845930-0e6d4f29-fe46-4456-b07e-1d87c492588c.png)

</table>

<table>
<tr>
	<td>

```jsx
<Text
  mt="small"
  mb="xlarge"
  style={{
    textAlign: 'center',
  }}
>
  My text
</Text>
```

   </td>
	<td>

![image](https://user-images.githubusercontent.com/9873486/136846148-affed8f9-4958-4068-90bb-da14f1f777ae.png)

</table>

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.5

**Additional context**

As you can see on the screenshots, other properties are working.

**Comment by caiotracera** [comment]
Hey @tcK1,

Hope you're doing well! 🌟
Just wanted to give you a heads-up that it seems like this issue has taken a bit of a nap and gone MIA. 😴 Since we're doing some cleanup, we're going to close it for now.

No worries though! If you think there's still life in it or if you've got more info to share, feel free to wake it up by reopening. Your input is always appreciated!

**Comment by caiotracera** [comment]
Hey @tcK1,

Hope you're doing well! 🌟
Just wanted to give you a heads-up that it seems like this issue has taken a bit of a nap and gone MIA. 😴 Since we're doing some cleanup, we're going to close it for now.

No worries though! If you think there's still life in it or if you've got more info to share, feel free to wake it up by reopening. Your input is always appreciated!
