### ISSUE TITLE
[BUG] Property `padding` already exists on `View` on Android, thus conflicting with the one coming from System

### ISSUE THREAD

**Issue by tcK1** [gympass/yoga#369]
**Describe the bug**
If we pass a property `padding` to the `Box` component, it errors on Android.

**To Reproduce**
1. Pass the property `padding` to the `Box` component with any value, e.g.: `small`.

**Expected behavior**
It should apply the correct padding.

**Smartphone (please complete the following information):**
 - Device: Galaxy S20+
 - OS: Android

**Comment by caiotracera** [comment]
Hey @tcK1,

Hope you're doing well! 🌟
Just wanted to give you a heads-up that it seems like this issue has taken a bit of a nap and gone MIA. 😴 Since we're doing some cleanup, we're going to close it for now.

No worries though! If you think there's still life in it or if you've got more info to share, feel free to wake it up by reopening. Your input is always appreciated!
