### ISSUE TITLE
[FEAT] Add variant prop to the Button component

### ISSUE THREAD

**Issue by dehmirandac2** [gympass/yoga#448]
**Is your feature request related to a problem? Please describe.**
The `Button` component on Yoga is created using dot notation (Button.Link). But when using this component I had a problem dealing with dynamic render.

The problem is that I can't add the `variant` value during a render based on a list, for example:

```js
<>
  {actions.map(({action, variant }) => (
     <Button onClick={action} variant={variant}>
       {text}
     </Button>
   ))}
</>
```

We can only call the component one by one:

```js
<Button.Link>text</Button.Link>
<Button.Outline>text</Button.Outline>
<Button.Text>text</Button.Text>
```

**Describe the solution you'd like**
As a solution, I would suggest adding a `variant` prop to the `Button` component, the same as used on[ Material UI](https://mui.com/components/buttons/). We can check if the variant has a value and return the right component based on a map. Something like this:

```js
const componentMap = {
    outline: Button.Outline,
    text: Button.Text,
    link: Button.Link,
  };

  const Component = variant ? componentMap[variant] : Button;

  return (
    <Component>{children}</Component>
  );
```

The idea of this implementation is to support both implementations: the **dot notation pattern** and the **variant prop**

**Comment by caiotracera** [comment]
Hey @dehmirandac2,

Hope you're doing well! 🌟
Just wanted to give you a heads-up that it seems like this issue has taken a bit of a nap and gone MIA. 😴 Since we're doing some cleanup, we're going to close it for now.

No worries though! If you think there's still life in it or if you've got more info to share, feel free to wake it up by reopening. Your input is always appreciated!
