### ISSUE TITLE
[FEAT] Add props to `Header` component

### ISSUE THREAD

**Issue by diogoverde** [gympass/yoga#474]
**Is your feature request related to a problem? Please describe.**
The `Header` component has no option to remove the shadow for mobile present in the `Box` component that originates it. 
This option exists in the figma design [file](https://www.figma.com/file/wn9grDi9mM29Wt7LmQjol7/%E2%9C%85-Yoga-%5BMAIN%5D?node-id=20243%3A101373).

**Describe the solution you'd like**
Add props to the Header component to able to remove these shadows if needed.

**Describe alternatives you've considered**
We have tried changing the component itself, removing the shadow which should not be the solution and it still does not work, since the shadow comes from the `Box` component itself.

**Additional context**
In case the figma link is not accessible I'll leave a screenshot here for ease of use.
![Screenshot 2022-05-20 at 16 55 02](https://user-images.githubusercontent.com/20834174/169566300-6fbdbbe4-26a6-40ae-99cf-f370ebd43e99.png)

**Comment by caiotracera** [comment]
Hey @diogoverde,

Hope you're doing well! 🌟
Just wanted to give you a heads-up that it seems like this issue has taken a bit of a nap and gone MIA. 😴 Since we're doing some cleanup, we're going to close it for now.

No worries though! If you think there's still life in it or if you've got more info to share, feel free to wake it up by reopening. Your input is always appreciated!
