### ISSUE TITLE
[FEAT] Add prop inverted to input components

### ISSUE THREAD

**Issue by RuanRamalho** [gympass/yoga#593]
Hello, my name is Ruan and I would like to contribute to Yoga! 

Looking to Yoga docs, I noticed a possible feature for `<Input />` component. 

In the [Input props documentation](https://gympass.github.io/yoga/components/input/default#props) , I saw that it doesn't have the prop `inverted` as I found in the `<Button />` props, as the `<Button />` has support for dark mode and it is a form component, nothing fairer than the input acquiring support for dark mode with the prop `inverted` since it is also a form component. 

This is an example of the `<Input />` in white mode without a prop `inverted`

![image](https://user-images.githubusercontent.com/58890915/211038400-6c7b7655-fd86-4155-be75-d5d7fd33b6c7.png)

And this is an example of how `<Input />` component with `inverted` property should work

![image](https://user-images.githubusercontent.com/58890915/211038961-5a221bfe-069f-4dd5-8610-6ede01d7a4a7.png)

### Conclusion: 

In order to have a good practice, the `inverted` property is needed in the `<Input />` component as well as in the `<Button` /> component.

**Comment by caiotracera** [comment]
Hey @RuanRamalho,

Hope you're doing well! 🌟
Just wanted to give you a heads-up that it seems like this issue has taken a bit of a nap and gone MIA. 😴 Since we're doing some cleanup, we're going to close it for now.

No worries though! If you think there's still life in it or if you've got more info to share, feel free to wake it up by reopening. Your input is always appreciated!
